version: '3.8'

services:
 backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./backend:/app

 frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app

networks:
 app-network:
    driver: bridge